# ═══════════════════════════════════════════════════════════════════════════════
# Prometheus Configuration
# ═══════════════════════════════════════════════════════════════════════════════

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'springbatch'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['springbatch:8080']
        labels:
          application: 'springbatch'
          environment: 'docker'
